//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------
#ifndef SM_7SEGMENTS_H
#define SM_7SEGMENTS_H

extern const unsigned char sm_seven_segment[];

#endif // SM_7SEGMENTS_H