//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------
#ifndef SM_BLUETOOTH_ADV_H
#define SM_BLUETOOTH_ADV_H

extern const unsigned char sm_bluetooth_adv[];

#endif // SM_BLUETOOTH_ADV_H