//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------
#ifndef SM_MONO_H
#define SM_MONO_H

extern const unsigned char sm_mono[];

#endif // SM_MONO